import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SearchBar from "../components/search";
import { useEffect, useState } from "react";
import dayjs from "dayjs";
import { useRouter } from "next/router";
import axios from "axios";

interface Diary {
  title: string;
  contents: string;
  created_at: string;
}

const Home: NextPage = () => {
  const router = useRouter();
  const [diaries, setDiaries] = useState<Diary[]>();
  const [original, setOriginal] = useState<Diary[]>();
  useEffect(() => {
    axios({
      method: "get",
      url: "http://localhost:3000/api/diary",
    }).then((res) => {
      setDiaries(res.data);
      setOriginal(res.data);
    });
  }, []);

  // const goToDetail = (diary:Diary) => {
  //   if (original) {
  //     const originalIndex = original.findIndex(i => i.title === diary.title)
  //     router.push(`/diary/${originalIndex}`)
  //   }
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Baby Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {diaries && (
        <SearchBar
          original={original}
          diaries={diaries}
          setDiaries={setDiaries}
        />
      )}

      {diaries &&
        diaries.map((diary, index) => {
          return (
            <div
              style={{
                border: "1px solid black",
                marginBottom: "15px",
                padding: "10px",
                position: "relative",
              }}
              key={index}
              onClick={() => {
                if (original) {
                  const originalIndex = original.findIndex(
                    (item) => item.title === diary.title
                  );
                  router.push(`/diary/${originalIndex}`);
                }
              }}
            >
              <p
                style={{
                  position: "absolute",
                  top: "-25px",
                  backgroundColor: "white",
                }}
              >
                {diary.title}
              </p>
              <p className={styles.diaryContents}>{diary.contents}</p>
              <div style={{ textAlign: "end" }}>
                <p>{dayjs(diary.created_at).format("YYYY년 MM월 DD일")}</p>
              </div>
            </div>
          );
        })}
    </div>
  );
};

export default Home;
